name: pro_extensions
description: "A comprehensive collection of Dart and Flutter extensions to boost productivity and make coding easier and more readable."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

